### ISSUE TITLE
Implementing aws-s3-storage

### ISSUE THREAD

**Issue by richardcham22** [jsreport/jsreport-aws-s3-storage#1]
Im confused about the jsreport-core part.
Is it necessary or just an alternative for autodiscovery extensions?
Do you mind elaborating about the steps to take, because i cant seem to be able to run it. Should it work automatically with every template rendered?

**Comment by pofider** [comment]
> Is it necessary or just an alternative for autodiscovery extensions?

It is just alternative. Ignore it if you use full jsreport.

> Do you mind elaborating about the steps to take, because i cant seem to be able to run it. Should it work automatically with every template rendered?

This is not automatic. You need to opt in report saving in the rendering request. See it here
https://jsreport.net/learn/reports
